server:
  port: 9090
bootstrap:
  enabled: true
spring:
  session:
    store-type: jdbc
  devtools:
    livereload:
      enabled: true # misc tuning
logging:
  level:
    org:
      springframework:
        web: info
      hibernate:
        sql: info
        type: info
    com:
      vishnu:
        aggarwal: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} -- [%thread] -- %-5level -- %logger{36} --- %msg%n"
security:
  ignored: /**
management:
  context-path: /manage
  security:
    enabled: true
rest:
  application:
    url: "${REST_APPLICATION_URL:http://localhost:8080}"