server:
  port: 9090
  context-path: "/admin"
bootstrap:
  enabled: true
spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    org:
      springframework:
        web: info
      hibernate:
        sql: info
        type: info
    com:
      vishnu:
        aggarwal: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} -- [%thread] -- %-5level -- %logger{36} --- %msg%n"
rest:
  application:
    baseUrl: "${REST_APPLICATION_URL:http://localhost:8080}"
    contextPath: "/rest/api"