server:
  port: "${ADMIN_MODULE_SERVER_PORT:9090}"
  servlet:
    context-path: "${ADMIN_MODULE_CONTEXT_PATH:/admin}"
bootstrap:
  enabled: "${ADMIN_MODULE_BOOTSTRAP_ENABLED:true}"
spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      log-condition-evaluation-delta: true
      additional-paths: classpath:/templates/,classpath:/static/,classpath:/assets/
      additional-exclude: "**/*.js,**/*.css,**/*.html"
  output:
    ansi:
      enabled: detect
  banner:
    charset: UTF-8
logging:
  level:
    root: info
    org.quartz: info
    org.springframework.web: info
    org.springframework.security: debug
    org.hibernate.tool.hbm2ddl: info
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type: debug
    org.hibernate.stat: debug
    com.vishnu.aggarwal: info
    org.springframework.cache: trace
    org.springframework.aop.interceptor.PerformanceMonitorInterceptor: trace
    org.springframework.aop.interceptor.DebugInterceptor: trace
    org.springframework.aop.interceptor.SimpleTraceInterceptor: trace
    com.vishnu.aggarwal.rest.interceptor.MethodLogInterceptor: trace
  file: "${ADMIN_MODULE_LOGGING_FILE_PATH:/home/vishnu/Desktop/quartzscheduler/logs/admin/admin.log}"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} -- [User Token : %X{X-AUTH-TOKEN}] -- [Custom Request ID : %X{customRequestId}] -- [%thread] -- %-5level -- %logger{36} --- %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} -- [User Token : %X{X-AUTH-TOKEN}] -- [Custom Request ID : %X{customRequestId}] -- [%thread] -- %-5level -- %logger{36} --- %msg%n"
    dateformat: "yyyy-MMM-dd HH:mm:ss"
    level: "%5p"
rest:
  application:
    baseUrl: "${REST_MODULE_URL:http://localhost:7070}"
    host: "${REST_MODULE_HOST:localhost}"
    port: "${REST_MODULE_SERVER_PORT:7070}"
    contextPath: "${REST_MODULE_CONTEXT_PATH:/rest/api}"
