server:
  port: "${REST_MODULE_SERVER_PORT:9090}"
  servlet:
    context-path: "${ADMIN_MODULE_CONTEXT_PATH:/admin}"
bootstrap:
  enabled: "${BOOTSTRAP_ENABLED:true}"
spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      log-condition-evaluation-delta: true
  output:
    ansi:
      enabled: detect
  banner:
    charset: UTF-8
logging:
  level:
    root: info
    org.quartz: info
    org.springframework.web: info
    com.vishnu.aggarwal: info
  file: "${LOGGING_FILE_PATH:/home/vishnu/quartzscheduler/logging/admin.log}"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} -- [%thread] -- %-5level -- %logger{36} --- %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} -- [%thread] -- %-5level -- %logger{36} --- %msg%n"
    dateformat: "yyyy-MMM-dd HH:mm:ss"
    level: "%5p"
rest:
  application:
    baseUrl: "${REST_MODULE_URL:http://localhost:7070}"
    host: "${REST_MODULE_HOST:localhost}"
    port: "${REST_MODULE_SERVER_PORT:7070}"
    contextPath: "${REST_MODULE_CONTEXT_PATH:/rest/api}"